version: '3.9'
services:
  jupyter:
    image: jupyter/datascience-notebook
    container_name: jupyter
    ports:
      - "8002:8888"
    volumes:
      - ./work:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''
    environment:
      - TZ=Asia/Taipei  # 時區設定